global:
  scrape_interval:     5s   
  evaluation_interval: 5s   
  scrape_timeout:      4s

  # Label yang ditambahkan ke semua time series
  external_labels:
    monitor  : 'sepsis-icu-monitor'
    project  : 'msml-submission'

# Alert rules
rule_files:
  - "alert_rules.yml"

# Scrape configs
scrape_configs:

  # 1. Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # 2. Scrape model metrics dari exporter 
  - job_name: 'sepsis_model_metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8000']
        labels:
          service     : 'sepsis-icu-model'
          model_type  : 'xgboost'
          environment : 'local'
