name: Auto Preprocessing Sepsis

on:
  push:
    branches: [ main ]

jobs:
  preprocess:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          cd Eksperimen_SML_Naimatul-Ulumiyah
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Preprocessing
        run: |
          cd Eksperimen_SML_Naimatul-Ulumiyah
          python preprocessing/automate_Naimatul-Ulumiyah.py

      - name: Commit & Push Preprocessed Dataset
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🚀 Auto: Update sepsis_preprocessing by GitHub Actions"
          file_pattern: "Eksperimen_SML_Naimatul-Ulumiyah/preprocessing/sepsis_preprocessing/**"
          branch: ${{ github.ref_name }}
